# Generated by Django 4.2.7 on 2023-12-05 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='delivered_date',
            field=models.DateTimeField(null=True),
        ),
    ]
