# Generated by Django 4.2.7 on 2023-11-29 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendorapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='historicalperformance',
            table='HistoricalPerformance',
        ),
        migrations.AlterModelTable(
            name='purchaseorder',
            table='PurchaseOrder',
        ),
    ]
