# Generated by Django 4.2.7 on 2023-11-29 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendorapp', '0002_alter_historicalperformance_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='purchaseorder',
            table=None,
        ),
    ]
