# Generated by Django 4.2.7 on 2023-11-29 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendorapp', '0004_alter_purchaseorder_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='purchaseorder',
            table='purchaseorder',
        ),
    ]
