# Generated by Django 4.2.7 on 2023-11-29 06:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendorapp', '0006_alter_purchaseorder_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchaseorder', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='purchaseorder',
            table=None,
        ),
    ]
