# Generated by Django 4.2.7 on 2023-11-29 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorapp', '0007_alter_purchaseorder_vendor_alter_purchaseorder_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='items',
            field=models.JSONField(default={}, null=True),
        ),
    ]
