# Generated by Django 4.2.7 on 2023-11-29 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendorapp', '0009_alter_purchaseorder_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='acknowledgment_date',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='issue_date',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='items',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='order_date',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='po_number',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='quality_rating',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='status',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='vendor',
        ),
    ]
