# Generated by Django 4.2.7 on 2023-11-29 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorapp', '0013_purchaseorder_order_date_purchaseorder_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='items',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('CAN', 'Canceled'), ('COMP', 'Completed'), ('PEN', 'Pending')], default='pending', max_length=50),
        ),
    ]
