# Generated by Django 4.2.7 on 2023-11-30 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendorapp', '0020_alter_vendor_address_alter_vendor_contact_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='order_date',
            new_name='orderdate',
        ),
    ]
