# Generated by Django 4.2.7 on 2023-11-30 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendorapp', '0021_rename_order_date_purchaseorder_orderdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='orderdate',
            new_name='order_date',
        ),
    ]
